### ISSUE TITLE
Xamarin Studio 6.1.2 (build 44) error on Windows 7 64-bit

### ISSUE THREAD

**Issue by yellow-panther** [manixaist/AllPawnsMustDie#1]
Hello,
an error occured during loading the the AllPawnsMustDie.sln file:
**unknown solution item type** - **Gandalf ChessGUI** https://github.com/ConorGriffin37/chess uses a. sln-file too: cf. my description on http://computer-chess.org/doku.php?id=computer_chess:wiki:lists:gui_protocol_support_list > Developable / Discontinued / Faulty / Incomplete Chess GUIs (with download-links, if possible)

**Running the GUI under Xamarin Studio works now - thanks for the hint by Hermann Krause! 

click on chess-master\chess-master\GUI.sln from 26th September 2016 (2KB) - top left and select Release instead of Debug and then on the symbol triangle (in the form of an arrow) [to the left] , - Gandalf Chess GUI is opened - the Xamarin Studio contains now a red framed square** 

I have installed on my pc: 

Doxygen for Windows http://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.13-setup.exe 

GTK# for .NET https://dl.xamarin.com/GTKforWindows/Windows/gtk-sharp-2.12.44.msi 

Microsoft 4.6 .NET Framework https://www.microsoft.com/en-US/download/details.aspx?id=48130 

Microsoft Build Tools 2013 https://www.microsoft.com/en-us/download/details.aspx?id=40760 

Microsoft Visual C++ 2010 Redistributable Package (x86) 
https://www.microsoft.com/en-US/download/details.aspx?id=5555 

Microsoft Visual C++ 2010 Redistributable Package (x64) 
https://www.microsoft.com/en-US/download/details.aspx?id=14632 

Mono for Windows 64 bit https://download.mono-project.com/archive/5.0.1/windows-installer/mono-5.0.1.1-x64-0.msi 

Xamarin Studio for Windows https://dl.xamarin.com/MonoDevelop/Windows/XamarinStudio-6.1.2.44.msi

**Comment by manixaist** [comment]
I'm not sure what this is.  No idea about Gandalf chess or Xamarin studio, but the solution loads just fine in Visual Studio from a clean clone of the repo and I can run it both release and debug.
