### ISSUE TITLE
srep by srep explanation how your GUi can started with MS VS 2017

### ISSUE THREAD

**Issue by yellow-panther** [manixaist/AllPawnsMustDie#2]
I installed MS VS 2017 (German version) , but have very few experiences with this Microsoft product.
Honestly said, for .sln I tried out before Xamarin Studio.

**Could you explain me (step-by-step, preferably including screenshots ) how your GUI can be lauched with MS VS 2017 Community, please?** I am using Windows graphical chess interfaces like Arena, ChessGUI, WinBoard or Scid vs. PC for engine matches under WinBoard or UCI protocol.

WinBoard a.k.a. CECP can be found here: http://home.hccnet.nl/h.g.muller/engine-intf.html - http://hgm.nubati.net/CECP.html

**Comment by manixaist** [comment]
This is not a completed GUI, it is still very much a work in progress and just a pet project.  If you need a fully-functioning one, I would stick with Arena or Winboard.

There is no way currently for a user to play the engine via the GUI.  That is something I am working on.  

I can add screenshots later if it's still needed, but this should be all you need to do step wise to run it
1.  Install VS 2017 Community edition (free one)
2.  Clone this repository e.g. into c:\apmd
3.  Open the solution at c:\apmd\AllPawnsMustDie\AllPawnsMustDie.sln
4.  Press F5 to run it.
5. In the current state you must first load an engine.  Do this with "File->Load Engine"

If you select "File->New Game" not much will happen at this point, I think the board will just draw.
If you select "File->Self Play" the engine will play itself in a loop to exercise the portions I have hooked up so far.

The only UCI engine I have used so far for testing is stockfish8.

**Comment by yellow-panther** [comment]
Yes, it works with SF8 , but someone has hosted an **edition without MS Visual Studio** here; http://www.mediafire.com/file/m3peocnh40p3nox/AllPawnsMustDie-master.zip
The installation of Microsoft´s freeware is very time consuming, and I had no luck to launch the .sln-file with Xamarin Studio (in contrast of Gandalf Chess GUI, another .sln-file).

An enumeration of graphical user interfaces cf. **GUI Protocol list of CCWiki**
http://computer-chess.org/doku.php?id=computer_chess:wiki:lists:gui_protocol_support_list and **WinBoard/XBoard a.k.a. CECP** can be found on http://home.hccnet.nl/h.g.muller/engine-intf.html - http://hgm.nubati.net/CECP.html

**Comment by manixaist** [comment]
I have no idea why someone shared a non-working version of my repo on mediafire that has only been up a short time.  It wasn't me.  It obviously has no place being compared to GUIs that are working and tested against a list of engines.  One day perhaps.

As for Visual Studio, I'm using the free one.  It's powerful, it's free, and it's from the people that invented the language being used.  There is nothing special about the project in terms of referencing other assemblies or other private projects, so as long as a 3rd party implements sln support correctly, it should work.
