### ISSUE TITLE
Self play of Stockfish 8 x64 popcnt doesn´t work

### ISSUE THREAD

**Issue by yellow-panther** [manixaist/AllPawnsMustDie#20]
Hello,
I use the current version of your GUI, downloaded Microsoft VS 2017 Community (freeware),
extracted your chess application with WinRAR, and ticked on the .sln-file, then pressed <f5>
> a chessboard with 32 pieces appears (with white and grey squares), and the mode player vs. AI runs normally. But after a new game I selected "self play" - default setting 250ms and nothing happens on the screen - no moves are made. Why?

**Comment by yellow-panther** [comment]
functional key f5 was finally pressed to launch your interface

**Comment by manixaist** [comment]
If you grabbed it very recently self play was broken, sorry.  I actually just fixed self play, so it should work now if you sync up.

**Comment by manixaist** [comment]
This change a3980b047090d325e7b80ae2481852ace1ddcfb4
